In [57]:
#Maddy's python practice
import numpy as np
from numpy import random

In [58]:
print ("Hello everyone")

Hello everyone


In [59]:
A = np.random.randn(5,2)

In [60]:
A

array([[-0.23907223,  0.47730601],
       [ 0.63345931, -0.72196683],
       [ 0.37996475, -0.25055529],
       [ 1.43168734, -1.58131606],
       [-1.26246654, -0.0761657 ]])

In [61]:
v = np.random.randn(2,1)

In [62]:
v

array([[ 1.29982982],
       [-1.61019811]])

In [63]:
B = A@v
B

array([[-1.07931046],
       [ 1.98589892],
       [ 0.89733317],
       [ 4.40718203],
       [-1.51834979]])

In [64]:
C = np.random.randn(5,2)
B = A+C
B

array([[-0.90461376,  0.31401635],
       [ 0.4886296 , -0.33257204],
       [ 0.06591491,  0.63672689],
       [ 4.04912276, -1.20913817],
       [-1.99901852,  0.01016097]])

In [65]:
iterations = 10
v_list = np.empty(iterations)
v_list

array([0.90461376, 0.31401635, 0.4886296 , 0.33257204, 0.06591491,
       0.63672689, 4.04912276, 1.20913817, 1.99901852, 0.01016097])

In [66]:
vect_1 = np.random.randn(5,1)
vect_2 = np.random.randn(5,1)
num = np.vdot(vect_1,vect_2)
num

0.7249232597728632

In [67]:
vect_1 = vect_1/np.linalg.norm(vect_1)
num = np.linalg.norm(vect_1)
num

1.0

In [72]:
v_list = np.empty(20)
sum = 0
for i in range(20):
    v_list[i] = random.randint(-10,10)
    #print(v_list[i])
    sum += v_list[i]

In [85]:
average = sum/20
average1 = np.mean(v_list)
average2 = np.sum(v_list)/20
print(average," ",average1," ",average2)

0.45   0.45   0.45
