In [3]:
#Maddy's python practice
import numpy as np
from numpy import random

In [4]:
print ("Hello everyone")

Hello everyone


In [5]:
A = np.random.randn(5,2)

In [6]:
A

array([[-0.13018123,  0.1971036 ],
       [ 0.95290131,  1.42366854],
       [-0.11712797,  0.83200561],
       [-0.80981009,  0.06521082],
       [-0.35768169,  0.59319017]])

In [7]:
v = np.random.randn(2,1)

In [8]:
v

array([[ 0.69010183],
       [-1.26683125]])

In [9]:
B = A@v
B

array([[-0.3395353 ],
       [-1.14594885],
       [-1.13484093],
       [-0.64146253],
       [-0.99830863]])

In [10]:
C = np.random.randn(5,2)
B = A+C
B

array([[ 0.53775203,  1.26214428],
       [-0.22190866,  1.48034912],
       [-1.43624135,  0.45332798],
       [-1.84204154, -1.55102552],
       [ 1.49171612,  2.29997546]])

In [11]:
iterations = 10
v_list = np.empty(iterations)
v_list

array([0.53775203, 1.26214428, 0.22190866, 1.48034912, 1.43624135,
       0.45332798, 1.84204154, 1.55102552, 1.49171612, 2.29997546])

In [12]:
vect_1 = np.random.randn(5,1)
vect_2 = np.random.randn(5,1)
num = np.vdot(vect_1,vect_2)
num

-1.3078871933003744

In [13]:
vect_1 = vect_1/np.linalg.norm(vect_1)
num = np.linalg.norm(vect_1)
num

1.0

In [14]:
v_list = np.empty(20)
sum = 0
for i in range(20):
    v_list[i] = random.randint(-10,10)
    #print(v_list[i])
    sum += v_list[i]

In [15]:
average = sum/20
average1 = np.mean(v_list)
average2 = np.sum(v_list)/20
print(average," ",average1," ",average2)

0.05   0.05   0.05


In [16]:
print("changing test")

changing test


In [42]:
#testing conjugate matrix
A = np.random.randint(10, size=(2, 3))
B = np.asmatrix(A)
AC = B.getH()
AC @A

matrix([[81, 63, 18],
        [63, 85, 56],
        [18, 56, 53]])